apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml

images:
  - name: 866567874348.dkr.ecr.ap-south-1.amazonaws.com/opsboard-backend
    newTag: 9fc4c3a829b5
  - name: 866567874348.dkr.ecr.ap-south-1.amazonaws.com/opsboard-frontend
    newTag: 9fc4c3a829b5
    
commonLabels:
  environment: prod
