apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsboard-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/yourorg/yourrepo.git'
    path: k8s/overlays/staging
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false # Terraform already creates the staging namespace
