apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base


patches:
- path: patch-replicas.yaml

images:
- name: 866567874348.dkr.ecr.ap-south-1.amazonaws.com/opsboard-backend
  newName: 866567874348.dkr.ecr.ap-south-1.amazonaws.com/opsboard-backend
  newTag: 57245f8685f9
- name: 866567874348.dkr.ecr.ap-south-1.amazonaws.com/opsboard-frontend
  newName: 866567874348.dkr.ecr.ap-south-1.amazonaws.com/opsboard-frontend
  newTag: 57245f8685f9

commonLabels:
  environment: staging
